version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents node_modules overwrite
    working_dir: /app
    command: npm run dev
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev 
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  flask-api:
    build:
      context: ./flask-api
      dockerfile: Dockerfile.dev
    volumes:
      - ./flask-api:/app
    working_dir: /app
    command: sh -c "python preload_data.py && python app.py"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
